appName: paymentservice
appImage: gcr.io/google-samples/microservices-demo/paymentservice
appVersion: v0.5.1
appReplicas: 2
containerPort: 50051
containerEnvVars:
  - name: PORT
    value: "50051"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"
  - name: DISABLE_DEBUGGER
    value: "1"  

serviceType: ClusterIP
servicePort: 50051
